config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  get 'contact', to: 'contacts#new'
  get 'about', to: 'about#index'
  get 'comments/new'
  get 'categories/show'

  resources 'posts', only: [:index, :show]
  resources 'contacts', only: [:new, :create]
  resources 'categories'

  namespace :admin do
    resources :categories, :users, :posts, :comments
    resources :sessions, only: [:new, :create]
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'
    get 'comments/destroy'
  end

  resources :posts do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts

  validates :name, presence: true

  def self.search(query)
    where("name like ?", "%#{query}%")
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :comments
  has_one_attached :image_file
  has_rich_text :body

  validates :title, presence: true
  validates :category_id, presence:true
  validates :body, presence: true

  def self.search(query)
    where("title like ? OR body like?", "%#{query}%", "%#{query}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
  before_save :encrypt_password

  has_many :posts

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  validates :password, confirmation: true

  def self.authenticate(email, password)
    user = find_by(email: email)
    if user.present? && user.password_hash == BCrypt::Engine.hash_secret(password.join, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.search(query)
    where("name like ? OR email like?", "%#{query}%", "%#{query}%")
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @posts = @category.posts
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    flash[:notice] = 'Comment Added'

    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:name, :email, :body, :post_id)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new

  end

  def create
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    if params[:search]
      @posts = Post.search(params[:search]).order('created_at DESC').paginate(per_page: 10, page: params[:page])
    else
      @posts = Post.all.order('created_at DESC').paginate(per_page: 10, page: params[:page])
    end
    @categories = Category.all
  end

  def show
    @post = Post.find(params[:id])
    @categories = Category.all
    @comment = Comment.new
    @comments = Comment.all
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/partials/_footer.html.erb
<p>Copyright &copy; 2014, rBlog | <%= link_to 'Back', root_path, class:'orange' %></p>

app/views/admin/partials/_search.html.erb
<% if params[:controller] == 'admin/posts' %>
  <%= form_tag(admin_posts_path, method: 'get', id: 'search-form', class: 'd-flex search-form') do %>
    <%= text_field_tag :search, params[:search], placeholder: 'Search Posts', class: ' form-control me-2' %>
    <%= submit_tag 'Search', name: nil, class: 'btn btn-primary' %>
  <% end %>
<% elsif params[:controller] == 'admin/categories'%>
  <%= form_tag(admin_categories_path, method: 'get', id: 'search-form', class: 'd-flex search-form') do %>
    <%= text_field_tag :search, params[:search], placeholder: 'Search Categories', class: ' form-control me-2' %>
    <%= submit_tag 'Search', name: nil, class: 'btn btn-primary' %>
  <% end %>
<% elsif params[:controller] == 'admin/users' %>
  <%= form_tag(admin_users_path, method: 'get', id: 'search-form', class: 'd-flex search-form') do %>
    <%= text_field_tag :search, params[:search], placeholder: 'Search Users', class: ' form-control me-2' %>
    <%= submit_tag 'Search', name: nil, class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RBlog</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="admin-style">
<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="index.html"><h1>rBlog<span>/Manager</span></h1></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Posts', admin_posts_path, class: "nav-link #{params[:controller] == 'admin/posts' ? 'active' : ''}" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Categories', admin_categories_path, class: "nav-link #{params[:controller] == 'admin/categories' ? 'active' : ''}" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Users', admin_users_path, class: "nav-link #{params[:controller] == 'admin/users' ? 'active' : ''}" %>
        </li>
      </ul>
      <%= render 'admin/partials/search' %>
    </div>
  </div>
</nav>
<!--/.Navbar-->

<section class="mt-5">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="card text-dark bg-light">
          <div class="card-body bg-light">
            <% if current_user %>
              <p class="text-end"><%= "Logged in as #{current_user.name}." %> <%= link_to 'Log out', admin_logout_path %></p>
            <% else %>
              <p class="text-end"><%= link_to 'Log in', admin_login_path %></p>
            <% end %>
            <!--flashes & messages-->
            <% if flash[:notice] %>
              <div class="alert alert-success">
                <%= flash[:notice] %>
              </div>
            <% end %>
            <% if flash[:alert] %>
              <div class="alert alert-danger">
                <%= flash[:alert] %>
              </div>
            <% end %>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<footer>
  <%= render 'admin/partials/footer' %>
</footer>

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="js/bootstrap.bundle.min.js"></script>

</body>
</html>

app/views/layouts/admin/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Login | RBlog</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body id='login-style'>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>