config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  get 'contact', to: 'contacts#new'
  get 'about', to: 'about#index'
  get 'comments/new'
  get 'categories/show'

  resources 'posts', only: [:index, :show]
  resources 'contacts', only: [:new, :create]
  resources 'categories'

  namespace :admin do
    resources :categories, :users, :posts, :comments
    resources :sessions, only: [:new, :create]
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'
    get 'comments/destroy'
  end

  resources :posts do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts

  validates :name, presence: true

  def self.search(query)
    where("name like ?", "%#{query}%")
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :comments
  has_one_attached :image_file
  has_rich_text :body

  validates :title, presence: true
  validates :category_id, presence:true
  validates :body, presence: true

  def self.search(query)
    where("title like ? OR body like?", "%#{query}%", "%#{query}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
  before_save :encrypt_password

  has_many :posts

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  validates :password, confirmation: true

  def self.authenticate(email, password)
    user = find_by(email: email)
    if user.present? && user.password_hash == BCrypt::Engine.hash_secret(password.join, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.search(query)
    where("name like ? OR email like?", "%#{query}%", "%#{query}%")
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :verify_logged_in

  def new
    @page_title = 'Add Category'
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category created'
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash[:notice] = 'Category Updated'
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def destroy
    @category.destroy
    flash[:notice] = 'Category Removed'
    redirect_to admin_categories_path
  end

  def index
    if params[:search]
      @categories = Category.search(params[:search]).all.order('created_at DESC').paginate(per_page: 10, page: params[:page])
    else
      @categories = Category.all.order('created_at DESC').paginate(per_page: 10, page: params[:page])
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :verify_logged_in

  def new
    @page_title = 'Add Posts'
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = 'Post Created'
      redirect_to admin_posts_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = 'Post Updated'
      redirect_to admin_posts_path
    else
      render :new
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = 'Post Removed'
    redirect_to admin_posts_path
  end

  def index
    if params[:search]
      @posts = Post.search(params[:search]).all.order('created_at DESC').paginate(per_page: 10, page: params[:page])
    else
      @posts = Post.all.order('created_at DESC').paginate(per_page: 10, page: params[:page])
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :user_id, :category_id, :tags, :image, :body, :image_file)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :verify_logged_in

  def new
    @page_title = 'Add User'
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'User created'
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = 'User Updated'
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def destroy
    @user.destroy
    flash[:notice] = 'User Removed'
    redirect_to admin_users_path
  end

  def index
    if params[:search]
      @users = User.search(params[:search]).all.order('created_at DESC').paginate(per_page: 10, page: params[:page])
    else
      @users = User.all.order('created_at DESC').paginate(per_page: 10, page: params[:page])
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @posts = @category.posts
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    flash[:notice] = 'Comment Added'

    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:name, :email, :body, :post_id)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new

  end

  def create
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    if params[:search]
      @posts = Post.search(params[:search]).order('created_at DESC').paginate(per_page: 10, page: params[:page])
    else
      @posts = Post.all.order('created_at DESC').paginate(per_page: 10, page: params[:page])
    end
    @categories = Category.all
  end

  def show
    @post = Post.find(params[:id])
    @categories = Category.all
    @comment = Comment.new
    @comments = Comment.all
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <!--check for errors-->
  <% if @category.errors.any?  %>
    <% @category.errors.full_messages.each do |msg| %>
      <!--show errors-->
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:'form-control' %>
  </div>
  <br>
  <%= f.submit 'Submit', class: 'btn btn-primary' %>
  <%= link_to 'Cancel', admin_categories_path, class: 'btn btn-default' %>
<% end %>

app/views/admin/categories/edit.html.erb
<h2>Edit Category</h2>
<%= render 'form', category: @category %>

app/views/admin/categories/index.html.erb
<h2 class="pb-2 mt-4 mb-2">Manage
  Categories <%= link_to 'Create New', new_admin_category_path, class: 'btn btn-success' %> </h2>
<% if @categories.exists? %>
  <table class="table table-striped">
    <tr>
      <th>Category Title</th>
      <th>Create Date</th>
      <th>Actions</th>
    </tr>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= l(category.created_at, format: '%d/%m/%Y - %H:%M') %></td>
        <td>
          <%= link_to 'Edit', edit_admin_category_path(category), class: 'btn btn-primary' %>
          <%= link_to 'Delete', admin_category_path(category), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= will_paginate @categories %>
<% else %>
  <p>There are no categories</p>
<% end %>

app/views/admin/categories/new.html.erb
<h2>Add New Category</h2>
<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<h2><%= @category.name %></h2>
<div class="row">
  <% if @posts.exists? %>
    <% @posts.each do |post| %>
      <div class="col-md-6">
        <div class="post">
          <% if post.image_file.present? %>
            <%= image_tag post.image_file, class: 'img-fluid' %>
          <% else %>
            <%= image_tag('rails1.jpg', class: 'img-fluid') %>
          <% end %>
          <div class="post-content">
            <h3><%= post.title %></h3>
            <small>Posted by <%= post.user.name %> on <%= l(post.created_at, format: '%d/%m/%Y - %H:%M') %></small>
            <p>
              <%= post.body.to_plain_text.truncate(200) %>
            </p>
            <div class="d-grid gap-2">
              <%= link_to 'Read More', post_path(post), class: 'btn btn-primary btn-lg' %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <p>No posts in this category yet</p>
  <% end %>
</div>